apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: yasuki-oshiro-pipeline-from-scratch-imagestream
  namespace: yasu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: builder
rules:
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
    verbs:
      - '*'
  - apiGroups:
      - image.openshift.io
    resources:
      - 'imagestreams/layers'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: builder
subjects:
  - kind: ServiceAccount
    name: build-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: builder
